### ISSUE TITLE
PHP exec execution 

### ISSUE THREAD

**Issue by niksmac** [JikkuJose/minksy#1]
I dont think the git hook with `exec` will work on any shared hosting providers. Because usually they don't allow access to these functions because they are potentially harmful. 

Something similar to,

```
disable_functions = "highlight_file,ini_alter,ini_restore,openly,passthru,phpinfo, exec, system, dl, fsockopen, set_time_limit,popen, proc_open, proc_nice,shell_exec,show_source,symlink"
```

**Comment by jikkujose** [comment]
Actually it works!
